-- Generated by pre-migration store at 7ac06f8a13b8ed630830bae51b38dc2f54067ebc; synthetic data only.
BEGIN TRANSACTION;
CREATE TABLE `ee_branding` (`id` integer,`logo` blob,`logo_mime` text,`logo_hash` text,`icon` blob,`icon_mime` text,`icon_hash` text,`updated_at` datetime,PRIMARY KEY (`id`));
INSERT INTO "ee_branding" VALUES(1,X'6C65676163792D6C6F676F','image/png','e4404852ff85cb7eba7203e675b4f0af46f0beaf4122e4c4dd28314a0e17dcc1',X'6C65676163792D69636F6E','image/jpeg','9459bc9c5bec5876450e88df661a0647b3b9c73690c88818a7c1ad509b6e7715','2026-09-10 18:25:28.240428+00:00');
CREATE TABLE `migrations` (`id` text,`sequence` integer,`applied_at` datetime,`status` text,PRIMARY KEY (`id`));
INSERT INTO "migrations" VALUES('ee_branding_v1',1,'2026-09-11 02:25:28.239995+08:00','success');
COMMIT;
